# Generated by Django 3.1.2 on 2020-12-20 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_remove_user_avatar'),
        ('product', '0002_auto_20201219_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='usercart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=64, verbose_name='商品名稱')),
                ('productId', models.IntegerField(verbose_name='商品編號')),
                ('productPrice', models.IntegerField(verbose_name='商品價格')),
                ('amount', models.IntegerField(verbose_name='商品數量')),
                ('avatar', models.ImageField(upload_to='productImage/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'usercart',
            },
        ),
    ]
