# Generated by Django 3.1.2 on 2020-12-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='null', max_length=255, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='null', max_length=64, verbose_name='電話號碼'),
        ),
    ]
