# Generated by Django 3.1.2 on 2020-12-31 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_remove_user_avatar'),
        ('product', '0002_auto_20201219_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartchoose',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productId', models.IntegerField(verbose_name='產品ID')),
                ('userId', models.IntegerField(verbose_name='用戶ID')),
                ('amount', models.IntegerField(verbose_name='數量')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'cart_choose',
            },
        ),
    ]
