# Generated by Django 3.1.2 on 2020-12-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='describe',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='product',
            name='event',
            field=models.TextField(blank=True, null=True, verbose_name='活動'),
        ),
    ]
